In [4]:
import numpy as np

In [5]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save('myarray',arr)

In [8]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [9]:
arr = np.arange(10)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('ziparray.npz',x = arr , y =np.arange(5))

In [13]:
archive_array = np.load('ziparray.npz')

In [15]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.savetxt('txtarray.txt', arr, delimiter = ',')

In [21]:
np.loadtxt('txtarray.txt',delimiter = ',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])